repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
    -   id: check-yaml
        exclude: .*templates/
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args: [--no-ensure-ascii,--autofix]
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]

-   repo: https://github.com/pappasam/toml-sort
    rev: v0.19.0
    hooks:
    -   id: toml-sort
        args: [--in-place]

-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: check-poetry

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: [--settings=pyproject.toml]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--config=.flake8]
default_language_version:
    python: python3.7
