# Continuous Integration (CI) Tests
version: '3.8'

services:
  sports-ci-test:
    container_name: sports-ci-test
    image: sports-ci-test
    build:
      context: .
      dockerfile: docker/Dockerfile-ci-tests
    networks:
      - "ci-test"
    ports:
      - "8086:8086"

networks:
  ci-test:
