version: '3.8'

services:
    sports-main:
        container_name: sports-main
        image: sports-main:$TAG
        build:
            context: .
            dockerfile: docker/Dockerfile
        networks:
            - "sports-main"
networks:
    sports-main:
